# Numpy

---------

In [3]:
import numpy as np

In [4]:
list_ = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
result = np.array(list_)

In [8]:
print(result)

[1 2 3 4 5 6 7 8 9]


-----------------

------------

In [84]:
import numpy as np 

In [89]:
result = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [90]:
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


-------------

-------------

In [91]:
import numpy as np 

In [95]:
result = np.array([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]], [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])

In [96]:
print(result)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


--------------------------

--------------

In [10]:
import numpy as np 

In [31]:
list_ = np.arange(0, 100).reshape(5, 20)

In [32]:
print(list_)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [33]:
print(list_.sum(axis = 0))

[200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
 290 295]


In [34]:
print(list_.sum(axis = 0).sum())

4950


In [35]:
print(list_.sum(axis = 1))

[ 190  590  990 1390 1790]


In [36]:
print(list_.sum(axis = 1).sum())

4950


-----------

-------------

In [37]:
import numpy as np 

In [43]:
print(np.zeros(50))               

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [44]:
print(np.ones(50))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [45]:
print(np.linspace(0, 1000, 50))

[   0.           20.40816327   40.81632653   61.2244898    81.63265306
  102.04081633  122.44897959  142.85714286  163.26530612  183.67346939
  204.08163265  224.48979592  244.89795918  265.30612245  285.71428571
  306.12244898  326.53061224  346.93877551  367.34693878  387.75510204
  408.16326531  428.57142857  448.97959184  469.3877551   489.79591837
  510.20408163  530.6122449   551.02040816  571.42857143  591.83673469
  612.24489796  632.65306122  653.06122449  673.46938776  693.87755102
  714.28571429  734.69387755  755.10204082  775.51020408  795.91836735
  816.32653061  836.73469388  857.14285714  877.55102041  897.95918367
  918.36734694  938.7755102   959.18367347  979.59183673 1000.        ]


In [47]:
print(np.random.random(5))  

[0.66502046 0.30671931 0.291382   0.99300069 0.75850813]


In [55]:
print(np.random.randint(0, 50, 10))

[34 35 18 24 29  4 19  0  4 21]


In [56]:
print(np.random.uniform(0, 50, 10))

[19.47046837 41.87030519 34.46281775 21.11627293 42.54526136 16.81962906
 26.11535302 35.21195948 23.76551838 27.65031507]


In [65]:
print(np.random.rand(10))

[0.87600645 0.06562552 0.01744929 0.81232169 0.12099015 0.01844676
 0.51535593 0.19463711 0.37679027 0.00137142]


In [66]:
print(np.random.randn(10))

[ 1.21157681 -0.45474948 -1.29312567 -0.38491994  0.61753437 -1.77956961
  1.81564305  0.61595184 -0.81432015  0.65045108]


In [72]:
print(np.random.ranf(20))

[0.05091104 0.65419848 0.12924834 0.18018087 0.01489322 0.88162783
 0.28651406 0.24514981 0.01525266 0.34765028 0.42897565 0.64673215
 0.21725782 0.73208312 0.68067754 0.06668098 0.85189357 0.31436367
 0.51379597 0.28512446]


----------

-----------------

In [73]:
import numpy as np 

In [74]:
result = np.random.randint(0, 100, 20)

In [76]:
print(result)

[59 40 10 33 96 30  1 88 40 59 85 12 30 70 36 46 95 21 90 48]


In [77]:
print(result.sum())

989


In [78]:
print(result.min())

1


In [79]:
print(result.max())

96


In [80]:
print(result.argmax())

4


In [81]:
print(result.argmin())

6


-----------

--------------

In [97]:
import numpy as np 

In [103]:
result_1 = np.random.randint(0, 100, 20)
result_2 = np.random.randint(0, 100, 20)
result_3 = np.random.randint(0, 100, 20)

In [104]:
print(result_1)

[54 38 93 54 54 81 41 90 86 42 88 52 94 97 61 86 93 39 59 48]


In [105]:
print(result_2)

[42 48 20 89 86 73 42 29 19 23 45 66 18 83 25 36 88 86 70 51]


In [106]:
print(result_3)

[50 99 96 24  6 20  7  8 46 35 81 48 84 61 73 20 12  6 84  5]


In [112]:
x_1 = np.hstack([result_1, result_2, result_3])

In [113]:
x_2 = np.vstack([result_1, result_2, result_3])

In [114]:
print(x_1)

[54 38 93 54 54 81 41 90 86 42 88 52 94 97 61 86 93 39 59 48 42 48 20 89
 86 73 42 29 19 23 45 66 18 83 25 36 88 86 70 51 50 99 96 24  6 20  7  8
 46 35 81 48 84 61 73 20 12  6 84  5]


In [115]:
print(x_2)

[[54 38 93 54 54 81 41 90 86 42 88 52 94 97 61 86 93 39 59 48]
 [42 48 20 89 86 73 42 29 19 23 45 66 18 83 25 36 88 86 70 51]
 [50 99 96 24  6 20  7  8 46 35 81 48 84 61 73 20 12  6 84  5]]
